### PR TITLE
Fix typespecs

### PR DESCRIPTION
**Pull request by alfert**
In order to type check this beautiful library, I needed to do some (mostly formal) fixes:

* added dialyxir (run `mix dialyzer`)
* introduced a new type for the `Repository` struct
* fixed the type of the banged functions

### CODE REVIEW

**Comment by tuvistavie** [comment]
Great, thank you very much!

**Comment by alfert** [comment]
Cool. Any chances for a release to hex.pm? I would love to use the new type `Git.Repository.t` in my Baumeister system.

**Comment by tuvistavie** [comment]
@alfert Published as 0.2.4, thanks for your help :smile:

**Comment by alfert** [comment]
Thanks for the quick release!

**Pull request merged**
